# Generated by Django 5.2.18 on 2026-10-08 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_max', models.PositiveIntegerField(default=199)),
                ('hr_lthr', models.PositiveIntegerField(default=177)),
                ('hr_rest', models.PositiveIntegerField(default=57)),
                ('threshold_power', models.PositiveIntegerField(default=411)),
                ('power_sport', models.CharField(default='running', max_length=12)),
                ('zone_limits', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('kind', models.CharField(choices=[('endurance', 'Bieg spokojny'), ('intervals', 'Interwały'), ('speed', 'Szybkość i sprinty'), ('strength', 'Siła'), ('mobility', 'Mobilność'), ('recovery', 'Regeneracja aktywna'), ('cycling', 'Rower'), ('test', 'Test sprawnościowy'), ('match_iii', 'Mecz · III liga'), ('match_district', 'Mecz · liga okręgowa'), ('match_assistant', 'Mecz · sędzia asystent'), ('other', 'Inna aktywność')], default='endurance', max_length=32)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('planned', 'Plan'), ('done', 'Wykonana')], default='planned', max_length=12)),
                ('duration_seconds', models.FloatField(default=0)),
                ('distance_km', models.FloatField(default=0)),
                ('avg_hr', models.PositiveIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveIntegerField(blank=True, null=True)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', max_length=12)),
                ('hr_segments', models.JSONField(default=list)),
                ('imported_filename', models.CharField(blank=True, max_length=200)),
                ('avg_power', models.PositiveIntegerField(blank=True, null=True)),
                ('max_power', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('date', 'slot'), name='two_daily_slots'), models.CheckConstraint(condition=models.Q(('slot__in', [1, 2])), name='valid_daily_slot')],
            },
        ),
    ]
